### ISSUE TITLE
What does notifyWsHeartBitExpired in your code mean?

### ISSUE THREAD

**Issue by sekharrockz** [instruritesh/ZStreamingQuote#2]
can you briefly explain on how are you using notifyWsHeartBitExpired in your library ? i am confused

**Comment by sekharrockz** [comment]
also can i know what does this function do ? "fireWSHeartBitMonitorTimer"

**Comment by instruritesh** [comment]
Zerodha Streaming Web Socket sends 1 Byte HeartBit packet when it has no quote data to send (to make the websocket remain alive). Now, any data whether quote packet or heartbit data will be received in WebsocketClientEndpoint.onMessage(ByteBuffer buffer) method.

But, we have to track whether our streaming web socket is alive or not. It may happen that for a long time any of the messages is not received but the socket is not closed also. It will remain open on client endpoint and no data will be updated, we will lose real time data in that case. That is why a timer has been started as soon as a message is received with preconfigured timeout. If any data is received again - it will stop this time and start a new one. If data is not received within that time frame, timer will trigger - it will close the existing socket connection and re initiate a new one, so that we dont loose out data.

notifyWsHeartBitExpired() method: First it will update the state of the websocket. Then, it will send unsubscribe command to server for the existing socket connection for which timer timed out of data. Then it will close the socket connection with argument as dont terminate i.e. we are closing the existing websocket connection, but we will not terminate the whole streaming flow, we want to reconnect again. => As soon as current socket is closed, websocket framework will trigger a notification of onClose(). Which in turn will call notifyWsSessionClosed() of the session notifier interface (that is implemented in WebsocketThread). There we check, if its a non terminating close happened, we will re initiate the websocket connection, subscribe and mode change. If its a terminating close happened, we will not re-initiate (which is ideally the end of whole system flow)
